=== XiaoshengLin/xmimsim/xml/xmimsim-1.0.dtd
<!ELEMENT xmimsim (general, composition , geometry, excitation, absorbers, detector)>

<!ELEMENT general (outputfile, n_photons_interval,n_photons_line,n_interactions_trajectory)>
<!ATTLIST general version CDATA #REQUIRED>
<!ELEMENT outputfile (#PCDATA)>
<!ELEMENT n_photons_interval (#PCDATA)>
<!ELEMENT n_photons_line (#PCDATA)>
<!ELEMENT n_interactions_trajectory (#PCDATA)>

<!ELEMENT composition (layer+, reference_layer)>
<!ELEMENT reference_layer (#PCDATA)>
<!ELEMENT layer (element+,density,thickness)>
<!ELEMENT element (atomic_number,weight_fraction)>
<!ELEMENT atomic_number (#PCDATA)>
<!ELEMENT weight_fraction (#PCDATA)>
<!ELEMENT density (#PCDATA)>
<!ELEMENT thickness (#PCDATA)>

<!ELEMENT geometry (d_sample_source, n_sample_orientation, p_detector_window, n_detector_orientation, area_detector, collimator_height, collimator_diameter, d_source_slit, slit_size)>
<!ELEMENT d_sample_source (#PCDATA)>
<!ELEMENT n_sample_orientation (x,y,z)>
<!ELEMENT p_detector_window (x,y,z)>
<!ELEMENT n_detector_orientation (x,y,z)>
<!ELEMENT area_detector (#PCDATA)>
<!--<!ELEMENT acceptance_detector (#PCDATA)>-->
<!ELEMENT collimator_height (#PCDATA)>
<!ELEMENT collimator_diameter (#PCDATA)>
<!ELEMENT d_source_slit (#PCDATA)>
<!ELEMENT slit_size (slit_size_x,slit_size_y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT sigma_x (#PCDATA)>
<!ELEMENT sigma_xp (#PCDATA)>
<!ELEMENT sigma_y (#PCDATA)>
<!ELEMENT sigma_yp (#PCDATA)>
<!ELEMENT slit_size_x (#PCDATA)>
<!ELEMENT slit_size_y (#PCDATA)>

<!ELEMENT excitation (discrete*,continuous*)>
<!ELEMENT discrete (energy, horizontal_intensity,vertical_intensity,sigma_x,sigma_xp,sigma_y, sigma_yp)>
<!ELEMENT continuous (energy, horizontal_intensity,vertical_intensity,sigma_x,sigma_xp,sigma_y, sigma_yp)>
<!ELEMENT energy (#PCDATA)>
<!ELEMENT horizontal_intensity (#PCDATA)>
<!ELEMENT vertical_intensity (#PCDATA)>

<!ELEMENT absorbers (excitation_path?,detector_path?)>
<!ELEMENT excitation_path (layer+)>
<!ELEMENT detector_path (layer+)>

<!ELEMENT detector (detector_type,gain,zero,fano,noise,max_convolution_energy,crystal)>
<!ELEMENT detector_type (#PCDATA)>
<!ELEMENT gain (#PCDATA)>
<!ELEMENT zero (#PCDATA)>
<!ELEMENT fano (#PCDATA)>
<!ELEMENT noise (#PCDATA)>
<!ELEMENT max_convolution_energy (#PCDATA)>
<!ELEMENT crystal (layer+)>

<!-- outputfile structure -->


<!ELEMENT xmimsim-results (inputfile, spectrum_conv, spectrum_unconv ,brute_force_history, variance_reduction_history?, xmimsim-input)>
<!ATTLIST xmimsim-results version CDATA #REQUIRED>
<!ELEMENT inputfile (#PCDATA)>
<!ELEMENT spectrum_conv (channel+)>
<!ELEMENT spectrum_unconv (channel+)>
<!ELEMENT channel (channelnr,energy,counts+)>
<!ELEMENT counts (#PCDATA)>
<!ATTLIST counts interaction_number CDATA #REQUIRED>
<!ELEMENT channelnr (#PCDATA)>
<!ELEMENT brute_force_history (fluorescence_line_counts*)>
<!ELEMENT variance_reduction_history (fluorescence_line_counts*)>
<!ELEMENT fluorescence_line_counts (#PCDATA)>
<!ATTLIST fluorescence_line_counts atomic_number CDATA #REQUIRED>
<!ATTLIST fluorescence_line_counts line_type CDATA #REQUIRED>
<!ATTLIST fluorescence_line_counts interaction_number CDATA #REQUIRED>
<!ELEMENT xmimsim-input (general, composition , geometry, excitation, absorbers, detector)>

=== XiaoshengLin/xmimsim/example/example1.xml
<?xml version="1.0"?>

<!--<!DOCTYPE xmimsim SYSTEM "http://www.xmi.UGent.be/xml/xmimsim-1.0.dtd"> -->
<!DOCTYPE xmimsim SYSTEM "/Volumes/Home/schoon/github/xmimsim/xml/xmimsim-1.0.dtd">

<xmimsim>
	<general version="1.0">
		<outputfile>test_output.txt</outputfile>
		<n_photons_interval>100000</n_photons_interval>
		<n_photons_line>10000</n_photons_line>
		<n_interactions_trajectory>4</n_interactions_trajectory>
	</general>
	<composition>
		<layer>
			<element>
				<atomic_number>7</atomic_number>
				<weight_fraction>75.55780</weight_fraction>
			</element>
			<element>
				<atomic_number>8</atomic_number>
				<weight_fraction>23.16160</weight_fraction>
			</element>
			<element>
				<atomic_number>18</atomic_number>
				<weight_fraction>0.96000</weight_fraction>
			</element>
			<density>1.22E-3</density>
			<thickness>3.0</thickness>
		</layer>
		<layer>
			<element>
				<atomic_number>14</atomic_number>
				<weight_fraction>46.73924</weight_fraction>
			</element>
			<element>
				<atomic_number>8</atomic_number>
				<weight_fraction>53.26076</weight_fraction>
			</element>
			<element>
				<atomic_number>20</atomic_number>
				<weight_fraction>60.0E-4</weight_fraction>
			</element>
			<element>
				<atomic_number>22</atomic_number>
				<weight_fraction>100.0E-4</weight_fraction>
			</element>
			<element>
				<atomic_number>24</atomic_number>
				<weight_fraction>80.0E-4</weight_fraction>
			</element>
			<element>
				<atomic_number>26</atomic_number>
				<weight_fraction>150.0E-4</weight_fraction>
			</element>
			<density>2.65</density>
			<thickness>0.2</thickness>
		</layer>
		<layer>
			<element>
				<atomic_number>7</atomic_number>
				<weight_fraction>75.55780</weight_fraction>
			</element>
			<element>
				<atomic_number>8</atomic_number>
				<weight_fraction>23.16160</weight_fraction>
			</element>
			<element>
				<atomic_number>18</atomic_number>
				<weight_fraction>0.96000</weight_fraction>
			</element>
			<density>1.22E-3</density>
			<thickness>3.0</thickness>
		</layer>
	</composition>
	<geometry>
		<d_sample_source>1000.0</d_sample_source>
		<n_sample_orientation>
			<x>0.0</x>
			<y>0.707107</y>
			<z>0.707107</z>
		</n_sample_orientation>
		<p_detector_window>
			<x>0.0</x>
			<y>-1.0</y>
			<z>1000.0</z>
		</p_detector_window>
		<n_detector_orientation>
			<x>0.0</x>
			<y>1.0</y>
			<z>0.0</z>
		</n_detector_orientation>
		<area_detector>0.30</area_detector>
		<acceptance_detector>1.57</acceptance_detector>
		<source_size>
			<sigma_x>0.0</sigma_x>
			<sigma_xp>0.0</sigma_xp>
			<sigma_y>0.0</sigma_y>
			<sigma_yp>0.0</sigma_yp>
		</source_size>
		<d_source_slit>1000.0</d_source_slit>
		<slit_size>
			<slit_size_x>0.001</slit_size_x>
			<slit_size_y>0.001</slit_size_y>
		</slit_size>
	</geometry>
	<excitation>
		<discrete>
			<energy>28.0</energy>
			<horizontal_intensity>2.9955e+12</horizontal_intensity>
			<vertical_intensity>4.5e+9</vertical_intensity>
		</discrete>
	</excitation>
	<absorbers>
		<detector_path>
			<layer>
				<element>
					<atomic_number>14</atomic_number>
					<weight_fraction>100.0</weight_fraction>
				</element>
				<density>2.33</density>
				<thickness>0.000010</thickness>
			</layer>
			<layer>
				<element>
					<atomic_number>4</atomic_number>
					<weight_fraction>100.0</weight_fraction>
				</element>
				<density>1.848</density>
				<thickness>0.00080</thickness>
			</layer>
		</detector_path>
	</absorbers>
	<detector><!-- watch units here...-->
		<detector_type>SiLi</detector_type>
		<gain>20.048138</gain>
		<zero>0.0</zero>
		<fano>0.12</fano>
		<noise>0.1</noise>
		<max_convolution_energy>35.0</max_convolution_energy>
		<crystal>
			<layer>
				<element>
					<atomic_number>14</atomic_number>
					<weight_fraction>100.0</weight_fraction>
				</element>
				<density>2.33</density>
				<thickness>0.5</thickness>
			</layer>
		</crystal>
	</detector>
</xmimsim>
